server:
  port: 8082

spring:
  application:
    name: compra-service
  datasource:
    url: jdbc:postgresql://localhost:5432/compra_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mercado-publico:
  licitacion:
    url: https://api.mercadopublico.cl/servicios/v1/publico
    ticket: A84949FD-A50D-40C4-A3D2-83791DFA28A3
  compra-agil:
    url: https://api2.mercadopublico.cl
    ticket: A84949FD-A50D-40C4-A3D2-83791DFA28A3
  adjuntos:
    url: https://adjunto.mercadopublico.cl/adjunto-compra-agil
    user-key: 41186b85826e80d1a0d445a6ce67d1a3
  auth:
    url: https://servicios-prd.mercadopublico.cl